# -*- coding: utf-8 -*-
"""EstagioTarget.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jN7A0xFi0BAAQc-0IDd-rvYGlho2riD
"""

def fibonnacci(num):

  if(num<0):
    print('O numero deve ser maior do que 0')
  elif(num==0):
    return 0

  elif(num==1 or num==2):
    return 1


  return fibonnacci(num-1) + fibonnacci(num-2)

def main():

  n = int(input("Digite o numero "))
  sequencia = []
  for i in range(n + 1):
        sequencia.append(fibonnacci(i))

  print("Sequencia de Fibonnacci:", sequencia)

  if n in sequencia:
        print(f'O numero {n} pertence a sequencia')
  else:
        print(f'O numero {n} nao pertence a sequencia')

  print(fibonnacci(n))

main()

INDICE = 12
SOMA = 0
K = 1
while K < INDICE:
  K = K + 1
  SOMA = SOMA + K;
  print(SOMA)

import string
minha_str = input('Digite uma string qualquer ')
conteA=0
for letter in minha_str:
  if letter == 'a' or letter == 'A':
    conteA = conteA + 1

if(conteA > 0):
  print(f'A letra a aparece {conteA} vezes')
elif(conteA==1):
  print(f'A letra A ou a aparece {conteA} vez')
else:
  print('A letra A ou a nao aparece')